FROM debian:latest

LABEL maintainer="Filip Valder <filip.valder@gmail.com>"

RUN apt-get update && \
    apt-get -y upgrade && \
    # prod dependencies
    apt-get -y install python3-flask && \
    # test/dev dependencies
    apt-get -y install python3-requests python3-pytest flake8 ack curl && \
    apt-get clean

RUN mkdir /src

COPY entrypoint.sh /entrypoint.sh

EXPOSE 5000

ENV PROJECT_ENV=dev

CMD ["/entrypoint.sh"]
